# Generated by Django 5.1.4 on 2025-01-14 14:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the department",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the department", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for department identification",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical"),
                            ("NURSING", "Nursing"),
                            ("DIAGNOSTIC", "Diagnostic"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("SUPPORT", "Support"),
                            ("AUXILIARY", "Auxiliary"),
                        ],
                        default="CLINICAL",
                        help_text="Type/category of the department",
                        max_length=20,
                    ),
                ),
                ("min_staff_per_shift", models.IntegerField(default=0)),
                ("emergency_min_staff", models.IntegerField(default=0)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the department",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location of the department (Floor/Wing/Building)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email for the department",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number for the department",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the department is currently active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the department was created",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the department was last updated",
                        null=True,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        help_text="Hospital this department belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="hospital.hospitalprofile",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent department if this is a sub-department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_departments",
                        to="staff.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospitalprofile",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "staff_member",
            },
        ),
        migrations.CreateModel(
            name="NurseProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("specialty_notes", models.TextField(blank=True)),
                ("emergency_response_qualified", models.BooleanField(default=False)),
                ("shift_preferences", models.JSONField(default=dict)),
                ("max_continuous_hours", models.IntegerField(default=12)),
                ("nurse_license", models.CharField(max_length=50, unique=True)),
                ("ward_specialty", models.CharField(max_length=100)),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_profile",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "nurse_profile",
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("specialty_notes", models.TextField(blank=True)),
                ("emergency_response_qualified", models.BooleanField(default=False)),
                ("shift_preferences", models.JSONField(default=dict)),
                ("max_continuous_hours", models.IntegerField(default=12)),
                ("specialization", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "availability",
                    models.JSONField(
                        default=dict, help_text="Weekly schedule in JSON format"
                    ),
                ),
                (
                    "consulting_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("max_patients_per_day", models.PositiveIntegerField(default=20)),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_profile",
            },
        ),
        migrations.CreateModel(
            name="DepartmentMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HEAD", "Department Head"),
                            ("DOCTOR", "Doctor"),
                            ("NURSE", "Nurse"),
                            ("TECHNICIAN", "Technician"),
                            ("STAFF", "Staff Member"),
                            ("ADMIN", "Administrative Staff"),
                        ],
                        help_text="Role of the staff member in the department",
                        max_length=30,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Date when the staff member started in this department"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the staff member ended their role (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the staff member's primary department",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Assignment"),
                            ("TEMPORARY", "Temporary Assignment"),
                            ("ROTATION", "Rotation"),
                            ("ON_CALL", "On-Call Coverage"),
                            ("TRAINING", "Training Period"),
                        ],
                        default="PERMANENT",
                        max_length=20,
                    ),
                ),
                (
                    "time_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of time allocated to this department",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "schedule_pattern",
                    models.JSONField(
                        default=dict, help_text="Weekly/monthly schedule pattern"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the assignment was created",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the assignment was last updated",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the assignment is currently active",
                    ),
                ),
                ("max_weekly_hours", models.IntegerField(default=40)),
                ("rest_period_hours", models.IntegerField(default=12)),
                ("emergency_contact", models.CharField(max_length=100)),
                ("is_emergency_response", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department the staff member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="staff.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User assigned to the department",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_memberships",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Member",
                "verbose_name_plural": "Department Members",
                "db_table": "department_member",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="department_head",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned as head of this department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="staff.staffmember",
            ),
        ),
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Medical Staff"),
                            ("NURSING", "Nursing Staff"),
                            ("ADMIN", "Administrative Staff"),
                            ("SUPPORT", "Support Staff"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="staff_roles", to="auth.permission"
                    ),
                ),
            ],
            options={
                "db_table": "staff_staffrole",
            },
        ),
        migrations.AddField(
            model_name="staffmember",
            name="role",
            field=models.ForeignKey(
                help_text="Role of the staff member in the department",
                on_delete=django.db.models.deletion.PROTECT,
                to="staff.staffrole",
            ),
        ),
        migrations.CreateModel(
            name="StaffTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Transfer"),
                            ("TEMPORARY", "Temporary Cover"),
                            ("ROTATION", "Rotation"),
                            ("EMERGENCY", "Emergency Reassignment"),
                        ]
                    ),
                ),
                ("reason", models.TextField()),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("required_documents", models.JSONField(default=list)),
                ("handover_checklist", models.JSONField(default=dict)),
                ("notice_period", models.IntegerField(default=30)),
                ("transition_notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.staffmember",
                    ),
                ),
                (
                    "from_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="staff.departmentmember",
                    ),
                ),
                (
                    "to_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="staff.departmentmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("specialty_notes", models.TextField(blank=True)),
                ("emergency_response_qualified", models.BooleanField(default=False)),
                ("shift_preferences", models.JSONField(default=dict)),
                ("max_continuous_hours", models.IntegerField(default=12)),
                ("technician_license", models.CharField(max_length=50, unique=True)),
                (
                    "equipment_specialties",
                    models.JSONField(
                        default=list, help_text="List of equipment specialties"
                    ),
                ),
                (
                    "lab_certifications",
                    models.JSONField(
                        default=list, help_text="List of laboratory certifications"
                    ),
                ),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_profile",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "technician_profile",
            },
        ),
        migrations.CreateModel(
            name="WorkloadAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                (
                    "scheduled_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("actual_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("on_call_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField()),
                ("break_duration", models.DurationField(blank=True, null=True)),
                ("is_overtime", models.BooleanField(default=False)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("ON_CALL", "On Call"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.departmentmember",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="departmentmember",
            index=models.Index(
                fields=["user", "department", "is_active"],
                name="department__user_id_2b3f1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmember",
            index=models.Index(
                fields=["role", "is_active"], name="department__role_ef574d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmember",
            index=models.Index(
                fields=["start_date", "end_date"], name="department__start_d_3af697_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmentmember",
            unique_together={("department", "user", "role")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["name", "hospital", "is_active"],
                name="department_name_ea6cf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["department_head"], name="department_departm_4c0f44_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__isnull", False)),
                name="department_name_not_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("code", "hospital")},
        ),
        migrations.AddIndex(
            model_name="staffrole",
            index=models.Index(
                fields=["name", "is_active"], name="staff_staff_name_1d4c34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["email", "is_active"], name="staff_membe_email_93cb66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["hospital", "role"], name="staff_membe_hospita_f8d93a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="staff_membe_first_n_6c4340_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffmember",
            constraint=models.CheckConstraint(
                condition=models.Q(("email__isnull", False)),
                name="staff_email_not_null",
            ),
        ),
    ]
