# Generated by Django 5.1.4 on 2025-01-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_alter_hospitalprofile_admin_user"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.hospitalprofile",
            ),
        ),
    ]
