# Generated by Django 5.1.4 on 2024-12-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="staffmember",
            table="staff_user",
        ),
    ]
