# Generated by Django 5.1.4 on 2025-01-09 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="department",
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(
                default="erfr",
                help_text="Unique code for department identification",
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email for the department",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Contact phone number for the department",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the department was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="department_head",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned as head of this department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[
                    ("CLINICAL", "Clinical"),
                    ("NURSING", "Nursing"),
                    ("DIAGNOSTIC", "Diagnostic"),
                    ("ADMINISTRATIVE", "Administrative"),
                    ("SUPPORT", "Support"),
                    ("AUXILIARY", "Auxiliary"),
                ],
                default="CLINICAL",
                help_text="Type/category of the department",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the department",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the department is currently active"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Physical location of the department (Floor/Wing/Building)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent department if this is a sub-department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_departments",
                to="staff.department",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the department was last updated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staffrole",
            name="category",
            field=models.CharField(
                choices=[
                    ("MEDICAL", "Medical Staff"),
                    ("NURSING", "Nursing Staff"),
                    ("ADMIN", "Administrative Staff"),
                    ("SUPPORT", "Support Staff"),
                ],
                default="MEDICAL",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffrole",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="hospital",
            field=models.ForeignKey(
                help_text="Hospital this department belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="hospital.hospitalprofile",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the department",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(help_text="Name of the department", max_length=100),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="role",
            field=models.ForeignKey(
                help_text="Role of the staff member in the department",
                on_delete=django.db.models.deletion.PROTECT,
                to="staff.staffrole",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("hospital", "code")},
        ),
        migrations.CreateModel(
            name="DepartmentMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the department member",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Date when the staff member started in this department"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the staff member ended their role (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the staff member's primary department",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the assignment was created",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the assignment was last updated",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the assignment is currently active",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department the staff member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="staff.department",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role of the staff member in the department",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.staffrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User assigned to the department",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_memberships",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Member",
                "verbose_name_plural": "Department Members",
                "db_table": "department_member",
                "ordering": ["-start_date"],
                "unique_together": {("department", "user", "role")},
            },
        ),
    ]
