# Generated by Django 5.1.4 on 2024-12-31 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("staff", "0002_alter_staffmember_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffmember",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="employment_date",
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="specialization",
        ),
        migrations.AddField(
            model_name="staffmember",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="staff.staffrole"
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
