# Generated by Django 5.1.4 on 2025-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_doctorprofile_user_alter_nurseprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="availability",
            field=models.JSONField(
                default=dict, help_text="Weekly schedule in JSON format", null=True
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nurseprofile",
            name="nurse_license",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="nurseprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nurseprofile",
            name="ward_specialty",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nurseprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="technicianprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="technicianprofile",
            name="technician_license",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="technicianprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
