# Generated by Django 5.1.4 on 2025-01-16 15:55

import apps.staff.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staffmember_hospital"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="departmentmember",
            name="department__start_d_3af697_idx",
        ),
        migrations.AddField(
            model_name="department",
            name="minimum_staff_required",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="departmentmember",
            name="schedule_pattern",
            field=models.JSONField(
                default=dict,
                help_text="Weekly/monthly schedule pattern",
                validators=[apps.staff.utils.validators.validate_schedule_pattern],
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmember",
            index=models.Index(
                fields=["start_date", "end_date", "time_allocation"],
                name="department__start_d_412281_idx",
            ),
        ),
    ]
