# Generated by Django 5.1.4 on 2025-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("HEAD", "Department Head"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("TECHNICIAN", "Technician"),
                    ("STAFF", "Staff Member"),
                    ("ADMIN", "Administrative Staff"),
                ],
                help_text="Role of the staff member in the department",
                max_length=30,
            ),
        ),
    ]
