# Generated by Django 5.1.4 on 2025-01-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "staff",
            "0003_remove_departmentmember_department__start_d_3af697_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="minimum_staff_required",
            field=models.IntegerField(default=0),
        ),
    ]
