# Generated by Django 5.1.4 on 2025-01-10 10:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hospital", "0001_initial"),
        ("staff", "0003_alter_departmentmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffrole",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="departmentmember",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="staffrole",
            name="code",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("code", "hospital")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["name", "hospital", "is_active"],
                name="department_name_ea6cf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["department_head"], name="department_departm_4c0f44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmember",
            index=models.Index(
                fields=["user", "department", "is_active"],
                name="department__user_id_2b3f1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmember",
            index=models.Index(
                fields=["role", "is_active"], name="department__role_ef574d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmember",
            index=models.Index(
                fields=["start_date", "end_date"], name="department__start_d_3af697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["email", "is_active"], name="staff_membe_email_93cb66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["hospital", "role"], name="staff_membe_hospita_f8d93a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="staff_membe_first_n_6c4340_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffrole",
            index=models.Index(
                fields=["name", "is_active"], name="staff_staff_name_1d4c34_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__isnull", False)),
                name="department_name_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffmember",
            constraint=models.CheckConstraint(
                condition=models.Q(("email__isnull", False)),
                name="staff_email_not_null",
            ),
        ),
    ]
