# Generated by Django 5.1.4 on 2025-01-11 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_remove_staffmember_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("specialty_notes", models.TextField(blank=True)),
                ("specialization", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "availability",
                    models.JSONField(
                        default=dict, help_text="Weekly schedule in JSON format"
                    ),
                ),
                (
                    "consulting_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("max_patients_per_day", models.PositiveIntegerField(default=20)),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_profile",
            },
        ),
        migrations.CreateModel(
            name="NurseProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("specialty_notes", models.TextField(blank=True)),
                ("nurse_license", models.CharField(max_length=50, unique=True)),
                ("ward_specialty", models.CharField(max_length=100)),
                (
                    "shift_preferences",
                    models.JSONField(
                        default=dict, help_text="Shift preferences in JSON format"
                    ),
                ),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_profile",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "nurse_profile",
            },
        ),
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                ("specialty_notes", models.TextField(blank=True)),
                ("technician_license", models.CharField(max_length=50, unique=True)),
                (
                    "equipment_specialties",
                    models.JSONField(
                        default=list, help_text="List of equipment specialties"
                    ),
                ),
                (
                    "lab_certifications",
                    models.JSONField(
                        default=list, help_text="List of laboratory certifications"
                    ),
                ),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_profile",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "technician_profile",
            },
        ),
    ]
