# Generated by Django 5.1.4 on 2025-01-13 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_doctorprofile_nurseprofile_technicianprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="emergency_min_staff",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="department",
            name="min_staff_per_shift",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("PERMANENT", "Permanent Assignment"),
                    ("TEMPORARY", "Temporary Assignment"),
                    ("ROTATION", "Rotation"),
                    ("ON_CALL", "On-Call Coverage"),
                    ("TRAINING", "Training Period"),
                ],
                default="PERMANENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="emergency_contact",
            field=models.CharField(default=3313123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="is_emergency_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="max_weekly_hours",
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="rest_period_hours",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="schedule_pattern",
            field=models.JSONField(
                default=dict, help_text="Weekly/monthly schedule pattern"
            ),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="time_allocation",
            field=models.DecimalField(
                decimal_places=2,
                default=21,
                help_text="Percentage of time allocated to this department",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="emergency_response_qualified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="max_continuous_hours",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="shift_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="emergency_response_qualified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="max_continuous_hours",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="technicianprofile",
            name="emergency_response_qualified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technicianprofile",
            name="max_continuous_hours",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="technicianprofile",
            name="shift_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="nurseprofile",
            name="shift_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="StaffTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Transfer"),
                            ("TEMPORARY", "Temporary Cover"),
                            ("ROTATION", "Rotation"),
                            ("EMERGENCY", "Emergency Reassignment"),
                        ]
                    ),
                ),
                ("reason", models.TextField()),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("required_documents", models.JSONField(default=list)),
                ("handover_checklist", models.JSONField(default=dict)),
                ("notice_period", models.IntegerField(default=30)),
                ("transition_notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.staffmember",
                    ),
                ),
                (
                    "from_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="staff.departmentmember",
                    ),
                ),
                (
                    "to_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="staff.departmentmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkloadAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                (
                    "scheduled_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("actual_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("on_call_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField()),
                ("break_duration", models.DurationField(blank=True, null=True)),
                ("is_overtime", models.BooleanField(default=False)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("ON_CALL", "On Call"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.departmentmember",
                    ),
                ),
            ],
        ),
    ]
