# Generated by Django 5.1.4 on 2025-01-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_department_emergency_min_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[
                    ("CLINICAL", "Clinical"),
                    ("NURSING", "Nursing"),
                    ("DIAGNOSTIC", "Diagnostic"),
                    ("ADMINISTRATIVE", "Administrative"),
                    ("SUPPORT", "Support"),
                    ("AUXILIARY", "Auxiliary"),
                ],
                default="CLINICAL",
                help_text="Type/category of the department",
                max_length=20,
            ),
        ),
    ]
