services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.11
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=medicore_db
      - POSTGRES_USER=medicore_user
      - POSTGRES_PASSWORD=medicore_password
      - REDIS_HOST=localhost
      - DJANGO_SETTINGS_MODULE=medicore.settings
      - ENCRYPTION_KEY=${ENCRYPTION_KEY} # Added for encryption
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medicore_db
      - POSTGRES_USER=medicore_user
      - POSTGRES_PASSWORD=medicore_password

  redis:
    image: redis:7
    restart: unless-stopped
    network_mode: service:db
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
