[tool.black]
line-length = 88  # Adjust this to your preferred line length (default is 88)
target-version = ['py39', 'py310', 'py311', 'py312',]  # Target Python versions
skip-string-normalization = false  # If true, Black won't normalize string quotes
exclude = '''
/(
    \.venv
    | \.env
    | \.git
    | \.mypy_cache
    | \.tox
    | \.pytest_cache
    | build
    | dist
)/
'''
