# Generated by Django 5.1.4 on 2025-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("hospital", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="tenant",
            field=models.ManyToManyField(
                related_name="users",
                through="hospital.HospitalMembership",
                to="tenants.client",
            ),
        ),
        migrations.AddIndex(
            model_name="myuser",
            index=models.Index(
                fields=["email", "is_active"], name="core_user_email_c0c03f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="myuser",
            index=models.Index(
                fields=["phone_number"], name="core_user_phone_n_59ea9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="myuser",
            index=models.Index(
                fields=["first_name", "last_name"], name="core_user_first_n_7ed624_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="myuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("email__isnull", False)),
                name="staff_email_not_null",
            ),
        ),
    ]
