# Generated by Django 5.1.4 on 2025-01-12 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenantpermission_myuser_tenant_permissions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantpermission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tenantpermission",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantpermission",
            unique_together={("user", "schema_name")},
        ),
    ]
