# Generated by Django 5.1.4 on 2025-01-13 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_remove_myuser_tenant_permissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "Can View"),
                            ("add", "Can Add"),
                            ("change", "Can Change"),
                            ("delete", "Can Delete"),
                        ],
                        help_text="The type of permission granted",
                        max_length=10,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model this permission applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tenant_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_permissions",
                        to="core.tenantpermission",
                    ),
                ),
            ],
            options={
                "db_table": "core_model_permission",
                "unique_together": {
                    ("tenant_permission", "content_type", "permission_type")
                },
            },
        ),
    ]
