# Generated by Django 5.1.4 on 2025-01-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_rename_status_client_subscription_plan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="subscription_plan",
            new_name="status",
        ),
    ]
