# Generated by Django 5.1.4 on 2024-12-23 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_alter_domain_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.client"
            ),
        ),
    ]
