# Generated by Django 5.1.4 on 2025-02-07 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentMemberShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assignment_start", models.DateField()),
                ("assignment_end", models.DateField(blank=True, null=True)),
                (
                    "max_weekly_occurrences",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "department_member_shifts",
            },
        ),
        migrations.CreateModel(
            name="GeneratedShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("is_emergency_override", models.BooleanField(default=False)),
                (
                    "geo_location",
                    models.CharField(
                        blank=True,
                        help_text="Location tag for distributed facilities",
                        max_length=100,
                    ),
                ),
                (
                    "required_equipment",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Equipment needed for this shift",
                    ),
                ),
                ("override_reason", models.TextField(blank=True)),
                (
                    "prioritization",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine Appointments"),
                            ("URGENT", "Urgent Care"),
                            ("PROCEDURE", "Procedure Blocks"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "generated_shifts",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ShiftSwapRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
            ],
            options={
                "db_table": "shift_swap_requests",
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                        ],
                        default="WEEKLY",
                        max_length=10,
                    ),
                ),
                (
                    "recurrence_parameters",
                    models.JSONField(
                        default=dict,
                        help_text="e.g., {'interval': 1, 'days': ['MON', 'WED']}",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "role_requirement",
                    models.CharField(
                        choices=[
                            ("HEAD", "Department Head"),
                            ("DOCTOR", "Doctor"),
                            ("NURSE", "Nurse"),
                            ("TECHNICIAN", "Technician"),
                            ("STAFF", "Staff Member"),
                            ("ADMIN", "Administrative Staff"),
                        ],
                        default="DOCTOR",
                        max_length=30,
                    ),
                ),
                (
                    "rotation_group",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning"),
                            ("AFTERNOON", "Afternoon"),
                            ("NIGHT", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "max_consecutive_weeks",
                    models.PositiveIntegerField(
                        default=1, help_text="Max consecutive weeks for this template"
                    ),
                ),
                ("max_staff", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "shift_templates",
                "ordering": ["valid_from", "start_time", "rotation_group"],
            },
        ),
        migrations.CreateModel(
            name="UserShiftState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_shift_end", models.DateTimeField()),
                ("rotation_index", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "user_shift_state",
            },
        ),
    ]
