# Generated by Django 5.1.4 on 2025-02-01 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentmembershift",
            name="department_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_shifts",
                to="staff.departmentmember",
            ),
        ),
        migrations.AddField(
            model_name="generatedshift",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staff.department"
            ),
        ),
        migrations.AddField(
            model_name="generatedshift",
            name="override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overridden_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedshift",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shiftswaprequest",
            name="original_shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swap_requests_as_original",
                to="scheduling.generatedshift",
            ),
        ),
        migrations.AddField(
            model_name="shiftswaprequest",
            name="proposed_shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swap_requests_as_proposed",
                to="scheduling.generatedshift",
            ),
        ),
        migrations.AddField(
            model_name="shiftswaprequest",
            name="requesting_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swap_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_templates",
                to="staff.department",
            ),
        ),
        migrations.AddField(
            model_name="generatedshift",
            name="source_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scheduling.shifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="departmentmembershift",
            name="shift_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduling.shifttemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftswaprequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_shift_id__isnull", False)),
                name="original_shift_must_exist",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedshift",
            index=models.Index(
                fields=["start_datetime", "end_datetime"],
                name="generated_s_start_d_d28450_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmembershift",
            index=models.Index(
                fields=["assignment_start", "assignment_end"],
                name="department__assignm_36cd7f_idx",
            ),
        ),
    ]
