# Generated by Django 5.1.4 on 2025-02-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentmembershift",
            name="department_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_shifts",
                to="staff.departmentmember",
            ),
        ),
        migrations.AddField(
            model_name="generatedshift",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_templates",
                to="staff.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usershiftpreference",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usershiftstate",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weekendshiftpolicy",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.department",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="usershiftpreference",
            unique_together={("user", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="usershiftstate",
            unique_together={("user", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="weekendshiftpolicy",
            unique_together={("department",)},
        ),
    ]
