# Generated by Django 5.1.4 on 2025-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_departmentmembershift_department_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usershiftstate",
            name="last_shift_end",
            field=models.DateTimeField(null=True),
        ),
    ]
