# Generated by Django 5.1.4 on 2025-04-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_alter_usershiftstate_current_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usershiftpreference",
            name="availability",
        ),
    ]
