# Generated by Django 5.1.4 on 2025-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_remove_usershiftpreference_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="usershiftstate",
            name="weekend_shift_count",
            field=models.IntegerField(default=0),
        ),
    ]
