# Generated by Django 5.1.4 on 2024-12-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="ssn_encrypted",
            new_name="nin_encrypted",
        ),
    ]
