# Generated by Django 5.1.4 on 2025-01-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="patientappointment",
            name="unique_appointment_per_doctor_start_time",
        ),
    ]
