# Generated by Django 5.1.4 on 2025-01-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpatient",
            old_name="primary_contact",
            new_name="emergency_contact",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="primary_contact",
            new_name="emergency_contact",
        ),
    ]
