# Generated by Django 5.1.4 on 2025-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="patientoperation",
            name="patient_ope_operati_c943c2_idx",
        ),
        migrations.RemoveField(
            model_name="historicalpatientoperation",
            name="operation_time",
        ),
        migrations.RemoveField(
            model_name="patientoperation",
            name="operation_time",
        ),
        migrations.AddIndex(
            model_name="patientoperation",
            index=models.Index(
                fields=["operation_code"], name="patient_ope_operati_8a7383_idx"
            ),
        ),
    ]
