# Generated by Django 5.1.4 on 2025-01-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_nin"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdemographics",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
