# Generated by Django 5.1.4 on 2025-01-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_historicalpatientappointment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientoperation",
            name="notes",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpatientoperation",
            name="operation_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpatientoperation",
            name="surgeon",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientvisit",
            name="discharge_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpatientvisit",
            name="visit_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpatientvisit",
            name="ward_or_clinic",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientoperation",
            name="notes",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientoperation",
            name="operation_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="patientoperation",
            name="surgeon",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientvisit",
            name="discharge_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientvisit",
            name="visit_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="patientvisit",
            name="ward_or_clinic",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["date_of_birth"], name="patients_date_of_24544d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientaddress",
            index=models.Index(fields=["state"], name="patient_add_state_59b8a6_idx"),
        ),
        migrations.AddIndex(
            model_name="patientaddress",
            index=models.Index(fields=["city"], name="patient_add_city_e1fa70_idx"),
        ),
        migrations.AddIndex(
            model_name="patientallergy",
            index=models.Index(
                fields=["patient"], name="patient_all_patient_71e0e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientallergy",
            index=models.Index(fields=["name"], name="patient_all_name_8d7884_idx"),
        ),
        migrations.AddIndex(
            model_name="patientallergy",
            index=models.Index(
                fields=["severity"], name="patient_all_severit_e3fd33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientappointment",
            index=models.Index(
                fields=["appointment_date", "physician"],
                name="patient_app_appoint_86a471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientappointment",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="patient_app_status_76394a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientchroniccondition",
            index=models.Index(
                fields=["patient"], name="patient_chr_patient_86031e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientchroniccondition",
            index=models.Index(
                fields=["condition"], name="patient_chr_conditi_015f84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientchroniccondition",
            index=models.Index(
                fields=["diagnosis_date"], name="patient_chr_diagnos_30027b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdemographics",
            index=models.Index(fields=["gender"], name="patient_dem_gender_951d6d_idx"),
        ),
        migrations.AddIndex(
            model_name="patientdemographics",
            index=models.Index(
                fields=["blood_type"], name="patient_dem_blood_t_364bea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdemographics",
            index=models.Index(
                fields=["preferred_language"], name="patient_dem_preferr_b18c76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdemographics",
            index=models.Index(
                fields=["marital_status"], name="patient_dem_marital_aee90b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdemographics",
            index=models.Index(
                fields=["created_at"], name="patient_dem_created_9c30ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdiagnosis",
            index=models.Index(
                fields=["patient"], name="patient_dia_patient_13836d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdiagnosis",
            index=models.Index(
                fields=["diagnosis_date"], name="patient_dia_diagnos_9b0b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdiagnosis",
            index=models.Index(
                fields=["diagnosis_name"], name="patient_dia_diagnos_0f2135_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdiagnosis",
            index=models.Index(
                fields=["icd_code"], name="patient_dia_icd_cod_2032aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientmedicalreport",
            index=models.Index(
                fields=["patient"], name="patient_med_patient_f90d8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientmedicalreport",
            index=models.Index(fields=["title"], name="patient_med_title_420860_idx"),
        ),
        migrations.AddIndex(
            model_name="patientmedicalreport",
            index=models.Index(
                fields=["created_at"], name="patient_med_created_d7b0c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientmedicalreport",
            index=models.Index(
                fields=["updated_at"], name="patient_med_updated_47fee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientoperation",
            index=models.Index(
                fields=["operation_date", "surgeon"],
                name="patient_ope_operati_efedc5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientoperation",
            index=models.Index(
                fields=["operation_name", "operation_code"],
                name="patient_ope_operati_c943c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientvisit",
            index=models.Index(
                fields=["visit_date", "ward_or_clinic"],
                name="patient_vis_visit_d_fd66ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientvisit",
            index=models.Index(
                fields=["discharge_date", "patient"],
                name="patient_vis_dischar_c71203_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="patientallergy",
            table="patient_allergies",
        ),
        migrations.AlterModelTable(
            name="patientappointment",
            table="patient_appointments",
        ),
        migrations.AlterModelTable(
            name="patientchroniccondition",
            table="patient_chronic_conditions",
        ),
        migrations.AlterModelTable(
            name="patientdiagnosis",
            table="patient_diagnoses",
        ),
        migrations.AlterModelTable(
            name="patientemergencycontact",
            table="patient_emergency_contacts",
        ),
        migrations.AlterModelTable(
            name="patientmedicalreport",
            table="patient_medical_reports",
        ),
        migrations.AlterModelTable(
            name="patientoperation",
            table="patient_operations",
        ),
        migrations.AlterModelTable(
            name="patientvisit",
            table="patient_visits",
        ),
    ]
