# Generated by Django 5.1.4 on 2025-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
        ("staff", "0007_remove_staffmember_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpatientappointment",
            name="color_code",
        ),
        migrations.RemoveField(
            model_name="patientappointment",
            name="color_code",
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="patientappointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="valid_time_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientappointment",
            constraint=models.UniqueConstraint(
                fields=("physician", "start_time"),
                name="unique_appointment_per_doctor_start_time",
            ),
        ),
    ]
