# Generated by Django 5.1.4 on 2025-01-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patientdemographics_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdemographics",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientdemographics",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patientdemographics",
            name="employment_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientdemographics",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientdemographics",
            name="marital_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientdemographics",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientdemographics",
            name="race",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
