# Generated by Django 5.1.4 on 2025-01-06 15:32

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import now  # Import for timezone-aware datetime


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_historicalpatientoperation_notes_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="patientappointment",
            name="patient_app_appoint_86a471_idx",
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="appointment_time",
            field=models.TimeField(default="23:00:00"),  # Default corrected
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="category",
            field=models.CharField(default="General", max_length=100),  # Default corrected
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="color_code",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="last_modified",
            field=models.DateTimeField(blank=True, default=now, editable=False),
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientappointment",
            name="recurrence_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="appointment_time",
            field=models.TimeField(default="23:00:00"),  # Default corrected
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="category",
            field=models.CharField(default="General", max_length=100),  # Default corrected
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="color_code",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appointments",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_appointments",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="patientappointment",
            name="recurrence_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientappointment",
            name="appointment_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="historicalpatientappointment",
            name="physician",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"role__name": "Doctor"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="staff.staffmember",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Completed", "Completed"),
                    ("Rescheduled", "Rescheduled"),
                    ("Canceled", "Canceled"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="patientappointment",
            name="appointment_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patientappointment",
            name="physician",
            field=models.ForeignKey(
                limit_choices_to={"role__name": "Doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="staff.staffmember",
            ),
        ),
        migrations.AlterField(
            model_name="patientappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Completed", "Completed"),
                    ("Rescheduled", "Rescheduled"),
                    ("Canceled", "Canceled"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="patientappointment",
            index=models.Index(
                fields=["appointment_date", "appointment_time"],
                name="patient_app_appoint_3d31b7_idx",
            ),
        ),
    ]
