# Generated by Django 5.1.4 on 2025-01-03 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_patientdemographics_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX patient_pin_lower_idx ON patients (LOWER(pin));",
            reverse_sql="DROP INDEX patient_pin_lower_idx;",
        ),
         migrations.AlterField(
            model_name="patient",
            name="pin",
            field=models.CharField(max_length=15, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="pin",
            field=models.CharField(
                db_index=True,
                default=737823328,
                editable=False,
                max_length=10,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="nin",
            field=models.CharField(
                blank=True, help_text="Encrypted NIN", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientdemographics",
            name="allergies",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="patientdemographics",
            name="chronic_conditions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name="PatientMedicalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
