# Generated by Django 5.1.4 on 2025-01-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_historicalpatientappointment_department_and_more"),
        ("staff", "0010_alter_department_department_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientappointment",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"department_type": "CLINICAL"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="staff.department",
            ),
        ),
        migrations.AlterField(
            model_name="patientappointment",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"department_type": "CLINICAL"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment_department",
                to="staff.department",
            ),
        ),
        migrations.AlterField(
            model_name="patientappointment",
            name="physician",
            field=models.ForeignKey(
                limit_choices_to={"role__name": "Doctor"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="staff.staffmember",
            ),
        ),
    ]
