# Generated by Django 5.1.4 on 2025-01-06 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0004_remove_patientappointment_patient_app_appoint_86a471_idx_and_more",
        ),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientappointment",
            name="appointment_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="historicalpatientappointment",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalpatientappointment",
            name="last_modified",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="patientappointment",
            name="appointment_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="patientappointment",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medicines", models.TextField()),
                ("instructions", models.TextField(blank=True, null=True)),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="patients.patientappointment",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        limit_choices_to={"role__name": "Doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_prescriptions",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "prescriptions",
                "indexes": [
                    models.Index(
                        fields=["appointment"], name="prescriptio_appoint_6d01d6_idx"
                    ),
                    models.Index(
                        fields=["issued_by", "issued_date"],
                        name="prescriptio_issued__afb578_idx",
                    ),
                    models.Index(
                        fields=["issued_date"], name="prescriptio_issued__2660c8_idx"
                    ),
                ],
            },
        ),
    ]
