# Generated by Django 5.1.4 on 2025-01-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0005_patient_pin_alter_patient_gender_alter_patient_nin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="pin",
            field=models.CharField(
                db_index=True, editable=False, max_length=15, unique=True
            ),
        ),
    ]
