# Generated by Django 5.1.4 on 2025-01-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0005_alter_historicalpatientappointment_appointment_time_and_more",
        ),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prescription",
            new_name="PatientPrescription",
        ),
        migrations.RenameIndex(
            model_name="patientprescription",
            new_name="patient_pre_appoint_45a731_idx",
            old_name="prescriptio_appoint_6d01d6_idx",
        ),
        migrations.RenameIndex(
            model_name="patientprescription",
            new_name="patient_pre_issued__70343c_idx",
            old_name="prescriptio_issued__afb578_idx",
        ),
        migrations.RenameIndex(
            model_name="patientprescription",
            new_name="patient_pre_issued__a9e4dc_idx",
            old_name="prescriptio_issued__2660c8_idx",
        ),
        migrations.AlterModelTable(
            name="patientprescription",
            table="patient_prescriptions",
        ),
    ]
