# Generated by Django 5.1.4 on 2025-01-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_alter_patient_pin"),
    ]

    operations = [
         migrations.RunSQL(
            """
            CREATE SEQUENCE IF NOT EXISTS patient_pin_seq_middle
            START WITH 20
            INCREMENT BY 1
            MINVALUE 20
            MAXVALUE 99999
            CYCLE;
            """,
            """
            CREATE SEQUENCE IF NOT EXISTS patient_pin_seq_last
            START WITH 40
            INCREMENT BY 1
            MINVALUE 40
            MAXVALUE 99999
            CYCLE;
            """
        ),
        migrations.AlterField(
            model_name="patientmedicalreport",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
