# Generated by Django 5.1.4 on 2025-01-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_alter_patientmedicalreport_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="pin",
            field=models.CharField(
                db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
