# Generated by Django 5.1.4 on 2025-01-26 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitalprofile",
            old_name="staff",
            new_name="members",
        ),
        migrations.AlterUniqueTogether(
            name="hospitalmembership",
            unique_together={
                ("user", "hospital_profile", "tenant"),
                ("user", "tenant", "role"),
            },
        ),
    ]
