# Generated by Django 5.1.4 on 2025-01-13 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalprofile",
            name="admin_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
