# Generated by Django 5.1.4 on 2025-01-14 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_myuser_first_name_myuser_last_name_and_more"),
        ("hospital", "0002_alter_hospitalprofile_admin_user"),
        ("tenants", "0003_rename_subscription_plan_client_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalprofile",
            name="additional_staff",
            field=models.ManyToManyField(
                blank=True,
                related_name="associated_hospitals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="admin_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="administered_hospital",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="tenants.client",
            ),
        ),
        migrations.CreateModel(
            name="HospitalStaffMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospitalprofile",
                    ),
                ),
                (
                    "tenant_permission",
                    models.ForeignKey(
                        help_text="The staff member's role and permissions in this hospital",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenantpermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hospital_staff_membership",
                "unique_together": {("hospital", "user")},
            },
        ),
    ]
