# Generated by Django 5.1.4 on 2025-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_rename_staff_hospitalprofile_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalprofile",
            name="hospital_code",
            field=models.CharField(
                default="GFE",
                help_text="Unique 3-letter hospital code for PIN generation",
                max_length=3,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
