# Generated by Django 5.1.4 on 2025-01-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_hospitalprofile_hospital_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospitalmembership",
            options={
                "permissions": [("generate_patient_pin", "Can generate patient PINs")]
            },
        ),
    ]
