# Generated by Django 5.1.4 on 2025-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0004_alter_hospitalmembership_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalprofile",
            name="hospital_code",
            field=models.CharField(
                help_text="Unique 3-letter hospital code for PIN generation",
                max_length=4,
                unique=True,
            ),
        ),
    ]
