# Generated by Django 5.1.4 on 2025-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_alter_hospitalprofile_hospital_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalmembership",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
